# Generated by Django 4.2.16 on 2024-10-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='admin_button',
            field=models.BooleanField(default=False),
        ),
    ]
