# Generated by Django 4.2.16 on 2024-10-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_button_admin_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='base_button',
            field=models.BooleanField(default=False),
        ),
    ]
